language: php
php:
  - 7.0
sudo: false
notifications:
    email: false
cache:
    directories:
        - $HOME/.composer/cache
before_install:
  - composer self-update
install:
  - composer install --no-interaction
script: true